import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const pdfCurrency = (val) =>
  `Rs. ${Number(val || 0).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
  })}`;

export const generateReceiptPdf = (order) => {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("POS STORE", 105, 15, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Thank you for shopping with us", 105, 22, { align: "center" });

  doc.line(14, 28, 196, 28);

  doc.setFontSize(11);

  doc.text(`Order ID : ${order.identifier ?? "-"}`, 14, 38);

  doc.text(`Customer : ${order.customer ?? "-"}`, 14, 45);

  doc.text(`Payment : ${order.paymentMethod ?? "-"}`, 14, 52);

  doc.text(`Date : ${new Date().toLocaleString("en-IN")}`, 14, 59);

  // Product Table
  autoTable(doc, {
    startY: 68,
    head: [["Product", "MRP", "Discount", "Price", "Qty", "Total"]],
    body:
      order.entryList.map((item) => [
        item.product ?? "",
        pdfCurrency(item.mrp),
        pdfCurrency(item.unitDiscount),
        pdfCurrency(item.unitPrice),
        String(item.quantity),
        pdfCurrency(item.totalPrice),
      ]) || [],
    theme: "grid",
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [220, 38, 38], // red
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "center" },
      5: { halign: "right" },
    },
  });

  const finalY = (doc.lastAutoTable?.finalY || 100) + 10;

  // Totals Box
  doc.roundedRect(120, finalY, 70, 40, 3, 3);

  doc.setFontSize(10);

  doc.setFont("helvetica", "normal");
  doc.text(`Original Price`, 125, finalY + 8);

  doc.text(pdfCurrency(order.originalPrice), 185, finalY + 8, {
    align: "right",
  });

  doc.text(`Discount`, 125, finalY + 16);

  doc.text(pdfCurrency(order.discount), 185, finalY + 16, { align: "right" });

  doc.line(125, finalY + 21, 185, finalY + 21);

  doc.setFont("helvetica", "bold");

  doc.text(`Grand Total`, 125, finalY + 30);

  doc.text(pdfCurrency(order.totalPrice), 185, finalY + 30, { align: "right" });

  // Cash Details
  if (order.paymentMethod === "CASH") {
    doc.setFont("helvetica", "normal");

    doc.text(`Received`, 14, finalY + 15);

    doc.text(pdfCurrency(order.receivedAmount), 60, finalY + 15);

    doc.text(`Change`, 14, finalY + 23);

    doc.text(pdfCurrency(order.changeAmount), 60, finalY + 23);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height;

  doc.line(14, pageHeight - 25, 196, pageHeight - 25);

  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");

  doc.text("Thank you for shopping with us!", 105, pageHeight - 15, {
    align: "center",
  });

  doc.text("Generated by POS System", 105, pageHeight - 8, {
    align: "center",
  });

  return doc;
};
