export const authColors = {
  error: "#ff4444",
  errorBg: "#fff9f9",
};

export const authSharedStyles = {
  page: {
    minHeight: "100vh",
    background: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Segoe UI', sans-serif",
    padding: "40px 20px",
    boxSizing: "border-box",
  },
  leftPanel: {
    flex: 1,
    background: "#111111",
    color: "#ffffff",
    padding: "48px 40px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  panelIcon: {
    fontSize: "48px",
    marginBottom: "16px",
  },
  panelTitle: {
    fontSize: "20px",
    fontWeight: "800",
    margin: "0 0 12px",
    color: "#ffffff",
  },
  panelSubtitle: {
    fontSize: "13px",
    color: "rgba(255,255,255,0.85)",
    lineHeight: "1.6",
    margin: 0,
  },
  rightPanel: {
    flex: 1,
    background: "#ffffff",
    padding: "48px 40px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  title: {
    fontSize: "26px",
    fontWeight: "800",
    color: "#1a1a1a",
    margin: "0 0 8px",
  },
  subtitle: {
    fontSize: "13px",
    color: "#666666",
    margin: 0,
  },
  label: {
    display: "block",
    fontSize: "11px",
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: "6px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    border: "1px solid #d0d8e0",
    borderRadius: "4px",
    backgroundColor: "#ffffff",
    color: "#1a1a1a",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
  },
  inputError: { border: "1px solid #ff4444", backgroundColor: "#fff9f9" },
  errorText: { fontSize: "12px", color: "#ff4444", marginTop: "4px" },
  button: {
    width: "100%",
    padding: "14px 16px",
    background: "#000000",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "15px",
    fontWeight: "800",
    cursor: "pointer",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    boxShadow: "0 4px 12px rgba(0,0,0,0.18)",
    transition: "all 0.2s ease",
  },
  buttonDisabled: { background: "#999999", cursor: "not-allowed" },
  buttonHover: { background: "#d2d2d2", color: "#000000" },
  errorBox: {
    backgroundColor: "#fff0f0",
    border: "1px solid #ff6b6b",
    color: "#ff4444",
    borderRadius: "8px",
    padding: "12px 14px",
    fontSize: "13px",
    marginBottom: "16px",
    textAlign: "center",
  },
  footer: { textAlign: "center", marginTop: "18px", fontSize: "13px", color: "#666666" },
  link: { color: "#1a1a1a", fontWeight: "700", textDecoration: "none", marginLeft: "6px" },
};