export const C = {
    primary: "#000000",
    secondary: "#3c3c3c",
    gray: "#d1d5db",
    offWhite: "#f4f4f4",
    text: "#1a1a1a",
    muted: "#666666",
    white: "#ffffff",
    error: "#ff4444",
};

export const searchInputSt = {
    padding: "10px 14px",
    border: `1.2px solid ${C.gray}`,
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    color: C.text,
    fontSize: "13px",
    width: "260px",
    marginLeft: "16px",
    outline: "none",
    boxShadow: "none",
    height: "42px",
};

export const listSharedStyles = {
    page: {
        position: "fixed",
        top: "60px",
        right: 0,
        bottom: 0,
        backgroundColor: C.offWhite,
        fontFamily: "'Segoe UI', sans-serif",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        transition: "left 0.2s ease",
    },
    inner: {
        flex: 1,
        padding: "20px 24px",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
    },
    topRow: {
        display: "flex",
        alignItems: "center",
        marginBottom: "16px",
        flexShrink: 0,
        position: "relative",
    },
    backBtn: {
        padding: "8px 16px",
        backgroundColor: "transparent",
        color: C.primary,
        border: "1px solid transparent",
        borderRadius: "6px",
        fontSize: "13px",
        fontWeight: "600",
        cursor: "pointer",
        flexShrink: 0,
        transition: "all 0.2s ease",
        height: "42px",
    },
    title: {
        position: "absolute",
        left: "50%",
        transform: "translateX(-50%)",
        margin: 0,
        fontSize: "19px",
        fontWeight: "700",
        color: C.text,
        whiteSpace: "nowrap",
    },
    card: {
        background: C.white,
        borderRadius: "12px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
        border: `1px solid ${C.gray}`,
        flex: 1,
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
    },
    tableWrap: { overflowY: "auto", flex: 1 },
    table: { width: "100%", borderCollapse: "collapse" },
    th: {
        textAlign: "left",
        padding: "11px 14px",
        borderBottom: `2px solid ${C.gray}`,
        fontSize: "11px",
        color: C.muted,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: "0.6px",
        backgroundColor: "#ffffff",
        position: "sticky",
        top: 0,
    },
    tr: { borderBottom: "1px solid #e5e7eb", transition: "background 0.1s" },
    td: { padding: "11px 14px", fontSize: "13px", color: C.text },
    emptyRow: { textAlign: "center", padding: "48px", color: C.muted, fontSize: "13px" },
};

export const deleteModalSt = {
    modalOverlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.4)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        fontFamily: "'Segoe UI', sans-serif",
    },
    modalBox: {
        backgroundColor: "#fff",
        padding: "24px",
        borderRadius: "12px",
        boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
        width: "100%",
        maxWidth: "400px",
        textAlign: "center",
    },
    modalTitle: { margin: "0 0 10px 0", fontSize: "18px", fontWeight: "700", color: C.primary },
    modalText: { margin: "0 0 20px 0", fontSize: "14px", color: C.text, lineHeight: "1.5" },
    modalBtns: { display: "flex", gap: "12px", justifyContent: "center" },
    modalCancel: {
        padding: "9px 18px",
        backgroundColor: C.gray,
        color: C.text,
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        fontSize: "13px",
        fontWeight: "600",
    },
    modalConfirm: {
        padding: "9px 18px",
        backgroundColor: "#dc2626",
        color: "#fff",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        fontSize: "13px",
        fontWeight: "600",
    },
};
