export const statusPageStyles = {
  page: {
    minHeight: "100vh",
    background: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Segoe UI', sans-serif",
    padding: "40px 20px",
    boxSizing: "border-box",
    textAlign: "center",
  },
  card: {
    maxWidth: "440px",
  },
  icon: {
    fontSize: "56px",
    marginBottom: "20px",
  },
  code: {
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#999999",
    margin: "0 0 8px",
  },
  title: {
    fontSize: "26px",
    fontWeight: "800",
    color: "#1a1a1a",
    margin: "0 0 12px",
  },
  message: {
    fontSize: "14px",
    color: "#666666",
    lineHeight: "1.6",
    margin: "0 0 28px",
  },
  actions: {
    display: "flex",
    gap: "12px",
    justifyContent: "center",
  },
  button: {
    display: "inline-block",
    padding: "14px 28px",
    background: "#000000",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "800",
    cursor: "pointer",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    textDecoration: "none",
    boxShadow: "0 4px 12px rgba(0,0,0,0.18)",
  },
  buttonSecondary: {
    display: "inline-block",
    padding: "14px 28px",
    background: "#ffffff",
    color: "#1a1a1a",
    border: "1px solid #d0d8e0",
    borderRadius: "6px",
    fontSize: "13px",
    fontWeight: "800",
    cursor: "pointer",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    textDecoration: "none",
  },
};
