import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PropTypes from "prop-types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "POS Application",
  description: "Generated by create next app",
};

/**
 * @param {Object} props - Root layout props
 * @param {React.ReactNode} props.children - Child components
 */
export default function RootLayout({ children }) {
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
