name: Spring Boot Deploy

on:
  push:
    branches:
      - feature/sprint5_pod5_pranavp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: |
          cd POS
          mvn clean package

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd POS

            git pull origin main

            mvn clean package

            pkill -f application.jar || true

            nohup java -jar target/application.jar > spring.log 2>&1 &